### ISSUE TITLE
MQTT function

### ISSUE THREAD

**Issue by Emmegiemme** [doudz/zigate#6]
Hi Sébastien,
well done! 

I have seen that you have deployed the MQTT function as we discussed! 
As soon as possible (it means as soon as I will stop following "white rabbits" on my home automation project) I will give a shot and run a test with it! ;-)

Cheers!

**Comment by doudz** [comment]
Currently I use it with Home Assistant

**Comment by Emmegiemme** [comment]
Cool, I will try to use it with mosquitto on OpenHab

**Comment by doudz** [comment]
Closing since no update

**Comment by pdecat** [comment]
Hi @doudz, since you said you were doing it, I'm trying to integrate my ZiGate (plugged with USB-TTL module) with Home Assistant using your MQTT broker implementation as it certainly is the most elegant way to do it.

However I'm currently struggling figuring out the proper configuration.

Is device discovery supposed to work with [Home Assistant's MQTT discovery](https://www.home-assistant.io/docs/mqtt/discovery/)?

Are the topics for discovery, command and state supposed to match out of the box?
Or is customization needed?

Here what I've tried right now but I doubt this would ever work as Home Assistant expects the discovery topic to follow the `<discovery_prefix>/<component>/[<node_id>/]<object_id>/<>` format:

```
mqtt:
  discovery: true
  discovery_prefix: zigate/device_changed

light:
  - platform: mqtt
    command_topic: "zigate/command"
```

Also, I guess `state_value_template` are needed to extract values from messages as described at https://www.home-assistant.io/components/light.mqtt/

Would you mind sharing an example Home Assistant configuration snippet for your MQTT broker?

**Comment by pdecat** [comment]
Hmm, I just stumbled on https://github.com/Koenkk/zigbee2mqtt

**Comment by doudz** [comment]
Oh... That's what I was looking for before buying a zigate...

**Comment by doudz** [comment]
Currently my mqtt broker doesn't support discovery.
I'll send you a example of what I use on my system soon

**Comment by doudz** [comment]
```
sensor:
  - platform: mqtt
    state_topic: "zigate/attribute_changed/21d3/01/0402/0000"
    name: 'Temperature'
    unit_of_measurement: "°C"
    value_template: '{{ value_json.value }}'
```
This is a Xiaomi temperature sensor, addr 21d3, endpoint 01, cluster 0x0402, attribute 0x0000
